### PR TITLE
Proto updates + dependencies

### PR DESCRIPTION
**Pull request by Crazy-Duck**

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
@RJacksonm1 can you push 5.1.0 to npm? Think this wraps up most of the recent new stuff

**Comment by RJacksonm1** [comment]
Will do so in a moment. Are you signed up to NPM yourself?

I'm conscious of being a bottleneck for this project by being the sole keyholder to NPM, and @jimmydorry isn't fulfilling the candlelight promise he made to years ago to set himself up on npm. If you're up for it I can add you to the project on npm?

**Comment by Crazy-Duck** [comment]
Yeah I'm set up on npm: [Link](https://www.npmjs.com/~jobuyse)

**Comment by RJacksonm1** [comment]
Righto. 5.1.0 published and I've added you as a collaborator on npm, which I imagine means you can publish too. :)

**Comment by jimmydorry** [comment]
RIP. https://youtu.be/NoOhnrjdYOc

One day, maybe tomorrow. Probably a good idea to have redundancy, in case someone disappears. 👍

**Pull request merged**
