### PR TITLE
5.0.0 Release

### PR DESCRIPTION
**Pull request by Crazy-Duck**
5.0.0 release, all changes are listed in the Changelog

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
@RJacksonm1 can you push to npm?

**Comment by jimmydorry** [comment]
The big v5.0.0 ! This is a major milestone.

**Comment by RJacksonm1** [comment]
I have HAND TESTED (I ran `yarn test`.... manually?) this code myself, by really struggling to remember the login details to my many spare accounts.  Tests seem to work, `package.json`'s already tagged as 5.0.0, and npm is [NPM version](https://npmjs.org/package/dota2 "View this project on NPM")

Good work friends! I'd buy you all cake if I had money to buy you all cake. Check back in 6 months to see how the cake fund's looking.

**Comment by jimmydorry** [comment]
As always, the cake is a lie. It's almost TI time too... too bad I'll be busy working.

**Comment by RJacksonm1** [comment]
Ooh that's a point. If I have large enough cake fund by that time I might spend it on Seattle instead, although probably won't be at TI each & every day; I can't visit the same city 3 times and not actually do any touristy things.

**Pull request merged**
