### PR TITLE
add private chat functionality

### PR DESCRIPTION
**Pull request by salacryl**
As I promised, my first pull request.
Someone should take a look into that  PrivateChatInfoRequest function. Wasn't sure about it.

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Good job on the implementation! I'll check it out in the coming week to see if everything works on my end as well. However, could you be so kind as to make a new pull request with some slight modifications to retain consistency? All our other methods are lowerCamelCase. Furthermore, if there's request in the message name, we usually start the function name with request (requestPrivateChatInfo for example)

**Comment by salacryl** [comment]
Ofc. One Moment.

**Comment by Crazy-Duck** [comment]
I've looked into privateChatInfoRequest and I never seem to be receiving a response. Have you had responses for the function? If not you might have to nethook the client and verify if the function is actually used or not. If the function doesn't work it should be removed from the PR.

A few final remarks 
* the events thrown by the handlers should also be lowerCamelCase (privateChatInfo, ...)
* when throwing events try to order the parameters so the raw object comes last (I might do a refactoring in a future major release to invert this behaviour, but for now I'd rather we stay coherent)
* can you add README entries for the functions you've introduced?
* the additional parameter you've added to shareLobby needs to be done in a different pull request as it breaks the API

**Comment by salacryl** [comment]
I did. FYI: I don't find any function where the raw object isn't the last, I think I oversaw something?

**Comment by Crazy-Duck** [comment]
Never mind that part, I misread the code while skimming it. I thought result was the entire object instead of just the result code, it's fine the way you did it :) Could you just update your PR so the merge conflicts are resolved?

**Comment by salacryl** [comment]
Can you give me the hint were I can find those conflicts? I'm new to this github ( I've my own git-server, so I never was in need).

**Comment by Crazy-Duck** [comment]
Try to do a git pull from the upstream repo (so this one) in your local salacryl:staging repository. You should get a message saying there are merge conflicts. It works the same way as it would on your own git-server

**Comment by salacryl** [comment]
Oh man, my cold is so annoying; I forgot everything :) please ignore my mess ;)

**Comment by Crazy-Duck** [comment]
If you're having issues, you can also always create a new local branch based on the last version of the staging branch and paste your modifications in there. Since you're notably adding stuff and not changing existing code, this might be an easier way :p

**Comment by salacryl** [comment]
Yeah, just let me get well.

**Comment by Crazy-Duck** [comment]
alright, don't sweat it, no one's rushing you ;)

**Comment by salacryl** [comment]
But the changes in handles/chat.js and README.md must be fitting, right?

**Comment by Crazy-Duck** [comment]
Iif you make a new branch based on the upstream (so RJacksonm1's) staging branch, it will automatically be up to date with the latest version. If you paste your modifications (and only your modifications), there should be no merge conflicts, since you started from the latest files. The reason why you're getting merge conflicts right now, is because there have been modifications to the files you yourself are also trying to modify. So you have two choices: resolving the merge conflicts, by going over them one by one, making sure you add your changes without destroying the changes that were added since you made your fork, or creating a new branch based on the latest version and making your pull from that one

**Comment by qing5hu1** [comment]
@Crazy-Duck please add this, I tried adding my own privatechat admin functions and I broke everything.
Just need a privatechat invite and kick function to serve my needs 👍

**Comment by salacryl** [comment]
@qing5hu1 you can ask me, I can help you out.

**Comment by qing5hu1** [comment]
@salacryl Can you kindly add me on steam? 
https://steamcommunity.com/id/qinxiie/

**Comment by markrmessmore** [comment]
@salacryl @qing5hu1 - could either of you share with me your functioning code? I would like to incorporate this feature. Thanks.

**Pull request closed without merging**
