### PR TITLE
Bugfixes after protobufjs update

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Also includes very small protobuf update. @RJacksonm1 / @jimmydorry can either one of you push this to npm as soon as I merge it?

### CODE REVIEW

**Comment by jimmydorry** [comment]
I still don't have a key. I'll ping RJ on irc tomoz

**Comment by RJacksonm1** [comment]
Published on NPM

**Comment by Crazy-Duck** [comment]
Thanks @RJacksonm1 !

**Comment by jimmydorry** [comment]
U da best AFK contributer @RJacksonm1

**Pull request merged**
