### PR TITLE
Fix Party invite response

### PR DESCRIPTION
**Pull request by Prosto-Sanja**

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
I'll test if this fixes the bug temporarily. If it does, I'll pull, but we'll probably need to figure out the contents of the ping data

**Comment by Prosto-Sanja** [comment]
I made dome more research with nethook:
when you decline party invite, your `ping_data` is null
when you accept, it is a vey complex structure of some data
image

**Comment by Crazy-Duck** [comment]
Alright let's break this down:
* `relay_codes` : actually no clue.. @paralin do you have any idea what these are?
* `relay_pings` : your ping to each of the 22 GC servers (see your servers file for their IP's)
* `region_codes` : codes of the 5 regions for which you have the lowest ping, in ascending order
* `region_pings` : the pings to the servers listed in `region_codes` in the same order
* `region_ping_failed_bitmask` : bitmask indicating for which servers the ping failed

**Comment by paralin** [comment]
Not sure, I haven't been paying attention to the progression of the GC lately. I'd imagine it has something to do with the datagram routing stuff.

**Comment by Prosto-Sanja** [comment]
It suddenly makes sense, relay_codes are some kind of server ids or hashes, then it lists their pings(22 items), and then selects 5 best and list their pings again.

**Comment by Crazy-Duck** [comment]
@Prosto-Sanja leave out the client_version, it's not needed (we've omitted it in the lobby messages as well). Update the README with the description of both functions and I'll merge the pull.

**Comment by Crazy-Duck** [comment]
I think the relay codes might also correspond to the match groups (see [here](https://github.com/SteamDatabase/GameTracking/blob/master/dota/game/dota/pak01_dir/scripts/matchgroups.txt)).  I propose we do the following:
* Add a parameter ping_data to acceptPartyInvite. This parameter is a string of integers representing the pings. 
* Add a parameter to helper.js which contains the relay codes
* In acceptPartyInvite construct ping data based on the array of ping data received as parameter, or omit if not present

Thoughts?

**Pull request closed without merging**
