### PR TITLE
5.0.0 - Major documentation overhaul

### PR DESCRIPTION
**Pull request by Crazy-Duck**
Did a complete rewrite of the documentation. All API docs can now be generated based on the jsdoc. I used jsdoc2md to splice the docs into the README.

There's also been a slight refactoring here and there, see the new CHANGELOG.md for details. 

Finally, I found out that all the compound objects we get for 64bit integers are protobufjs converting them to long.js objects, so I did some internal refactoring to remove bignumber.js and replace it with long.js and I replaced all the instances where we did `"" + id1 === "" + id2` by proper equality checks

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Oh, I also added the examples to npmignore, since I feel like examples shouldn't be included in the distributed package

**Comment by jimmydorry** [comment]
Dayum, this library looks super fancy now. Great work. You are putting @RJacksonm1 to shame GreyFace

**Comment by RJacksonm1** [comment]
Top work, gentlemens. 👍

**Comment by rossengeorgiev** [comment]
@RJacksonm1 is alive? 🤔

**Pull request merged**
