### PR TITLE
Fix protobufjs breaking our shit

### PR DESCRIPTION
**Pull request by Crazy-Duck**
The new protobufjs minor release broke the lookup of enum's. This pull fixes everything they broke

### CODE REVIEW

**Comment by Crazy-Duck** [comment]
Tests pass, just time-out cause steam is slow

**Comment by howardchung** [comment]
Consider https://greenkeeper.io/ to automatically test new downstream updates, although we might get a lot of false positives with the steam GC not being very consistent

**Comment by howardchung** [comment]
Does this need to pushed as a hotfix (new npm version?)

**Comment by Crazy-Duck** [comment]
Probably yeah, I'll try and get it to the master branch as soon as possible. It's gonna be v5.0.1

**Pull request merged**
