### PR TITLE
Bump to 4.1.0

### PR DESCRIPTION
**Pull request by Crazy-Duck**
It's been a while since we've bumped the master branch and by now there's a few little things that are broken there. This should bring everything up to speed again. Tagging the regulars to see if anyone has any objections, if not, I'll merge.
@Arcana/dota @howardchung

### CODE REVIEW

**Comment by howardchung** [comment]
CI passing on MMR and match details and I'm good :)

**Comment by Crazy-Duck** [comment]
@RJacksonm1 Is your blog still live? I'm getting a 502 from your nginx server when testing the link (which btw, for a guy complaining about 2FA to his contributors, runs a surprisingly outdated version of nginx xD)

**Comment by Crazy-Duck** [comment]
@RJacksonm1 Can you update the npm package?

**Comment by jimmydorry** [comment]
haha rekt @RJacksonm1 (about nginx version)

**Pull request merged**
